name: "Collect IPs"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Set up Python
       - uses: actions/setup-python@v2
         with:
          python-version: 3.x
       - uses: actions/checkout@v3
       - name: Resolve domains, collect and store IP addresses
         run: |
          python -m pip install dnspython requests beautifulsoup4
          python ippq.py
          #python ipushkjp.py
          #python collect.py 
          git config --global user.email "chenhua.xu@qq.com"
          git config --global user.name "wokaotianshi123"
          git add -A
          git commit -m "Automatic update"
          git push
