name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:  # 允许提交触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run Python script
      run: |
        import requests
        from bs4 import BeautifulSoup
        import re

        url = 'https://monitor.gacjie.cn/page/cloudflare/ipv4.html'
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        rows = soup.find_all('tr')
        ip_pattern = r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'

        with open('ip.txt', 'w') as file:
            for row in rows:
                row_text = row.get_text()
                ip_matches = re.findall(ip_pattern, row_text)
                for ip in ip_matches:
                    file.write(ip + '\n')
        
    - name: Commit and push changes
      run: |
        git config --global user.email "chenhua.xu@qq.com"
        git config --global user.name "wokaotianshi123"
        git add ip.txt
        git commit -m "Update IP list"
        git push
